backend:
    name: github
    repo: danko-miadria/astro-test-website
    branch: master

# REQUIRED: Image and Media upload settings
media_folder: "public/uploads"
public_folder: "/uploads"

# REQUIRED: Content collections configuration
collections:
    - name: "blog"
      label: "Blog Posts"
      folder: "src/content/blog"
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - {
                label: "Description",
                name: "description",
                widget: "text",
                required: false,
            }
          - {
                label: "Featured Image",
                name: "thumbnail",
                widget: "image",
                required: false,
            }
          - { label: "Body", name: "body", widget: "markdown" }
