backend:
    name: github
    repo: danko-miadria/astro-test-website
    branch: master
    base_url: https://sveltia-cms-auth.danko-0b7.workers.dev
    auth_endpoint: /auth

# Where Decap CMS saves uploaded images in your GitHub repo
media_folder: "src/assets/images"

# How the image path is written inside the Markdown frontmatter/body for Astro
public_folder: "../../assets/images"

# Content collections configuration
collections:
    - name: "blog"
      label: "Blog Posts"
      folder: "src/posts/blog"
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      fields:
          - {
                label: "Layout",
                name: "layout",
                widget: "hidden",
                default: "../../pages/blog.astro",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - {
                label: "Description",
                name: "description",
                widget: "text",
                required: false,
            }
          - {
                label: "Featured Image",
                name: "thumbnail",
                widget: "image",
                required: false,
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
                label: "Rating",
                name: "rating",
                widget: "number",
                required: false,
            }
